### ISSUE TITLE
[Bug]: Compile error in scan-tsql-epilogue.l.c

### ISSUE THREAD

**Issue by Kretikus** [babelfish-for-postgresql/babelfish_extensions#1849] opened 2023-09-18 14:15 UTC
### What happened?

Tell us about the bug.

scan-tsql-epilogue.l.c: In function ‘pgtsql_core_yyfree’:
scan-tsql-epilogue.l.c:80:1: error: infinite recursion detected [-Werror=infinite-recursion]
scan-tsql-epilogue.l.c:82:2: note: recursive call
cc1: all warnings being treated as errors

Code in question: looks really like a recursion....
`
void
pgtsql_core_yyfree(void *ptr, core_yyscan_t yyscanner)
{
        pgtsql_core_yyfree(ptr, yyscanner);
}
`

### Version

BABEL_3_X_DEV (Default)

### Extension

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by timchang514** [comment] 2023-09-18 18:25
Hi, 

I can't replicate this on my local build. 

Tried this at babelfish_extensions:a4c38aedbae654525605ecfdf70d621016bc757d and postgresql_modified_for_babelfish:d06098345207be350f83f968db9081b87dbf8ee2. Can you provide more information on reproducing?

**Comment by staticlibs** [comment] 2023-09-22 18:30
This warning happens on newer versions of GCC, for example on Fedora 37:
```
$ gcc --version
gcc (GCC) 12.3.1 20230508 (Red Hat 12.3.1-1)
```
It looks like an obvious typo in `pgtsql_core_yyfree`, I've filed #1861 to fix it.

**Comment by Deepesh125** [comment] 2023-10-12 08:38
@Kretikus please confirm if above commit from @staticlibs fixes your issue. If it is the case then please consider closing this issue. Thanks!

**Closed as completed** 2023-12-15 13:51 UTC
Labels: Pending Response, build_issues
