### ISSUE TITLE
[Bug]: can't create local temporary table

### ISSUE THREAD

**Issue by sherbert** [babelfish-for-postgresql/babelfish_extensions#136] opened 2022-04-22 16:00 UTC
### Contact Details

herbert@dc-energy.com

### What happened?

Attempting to create a simple local temporary table is failing:
```
1> CREATE DATABASE foo
2> GO
1> USE foo
2> GO
Changed database context to 'foo'.
1> CREATE TABLE [dbo].[#bar] (baz INT)
2> GO
Msg 33557097, Level 16, State 1, Server BABELFISH, Line 1
could not open relation with OID 266369
```
I see in the documentation that global temporary tables (names starting with `##`) are not supported (and I do get a descriptive error saying as much if I attempt to create one), but did not find anything suggesting that local temporary tables shouldn't work.

### Version

BABEL_1_X_DEV (Default)

### Extension

babelfishpg_tsql (Default)

### What flavour of Linux are you running into the bug?

Ubuntu (Default)

### Relevant log output

```shell
2022-04-22 11:56:53.262 EDT [1186838] LOG:  Unmapped error found. Code: 2600, Message: could not open relation with OID 266369, File: relation.c, Line: 62, Context: babelfishpg_tsql
2022-04-22 11:56:53.262 EDT [1186838] CONTEXT:  PL/tsql function inline_code_block line 1 at SQL statement
        TDS Protocol: Message Type: SQL BATCH, Phase: TDS_REQUEST_PHASE_PROCESS. Processing SQL Batch Request
2022-04-22 11:56:53.262 EDT [1186838] LOG:  Unmapped error found. Code: 2600, Message: could not open relation with OID 266369, File: relation.c, Line: 62, Context: babelfishpg_tsql
2022-04-22 11:56:53.262 EDT [1186838] CONTEXT:  TDS Protocol: Message Type: SQL BATCH, Phase: TDS_REQUEST_PHASE_PROCESS. Processing SQL Batch Request
2022-04-22 11:56:53.262 EDT [1186838] ERROR:  could not open relation with OID 266369 at character 14
2022-04-22 11:56:53.262 EDT [1186838] QUERY:  CREATE TABLE [dbo].[#bar] (baz INT)
2022-04-22 11:56:53.262 EDT [1186838] CONTEXT:  PL/tsql function inline_code_block line 1 at SQL statement
        TDS Protocol: Message Type: SQL BATCH, Phase: TDS_REQUEST_PHASE_PROCESS. Processing SQL Batch Request
2022-04-22 11:56:53.262 EDT [1186838] LOG:  Unmapped error found. Code: 2600, Message: could not open relation with OID 266369, File: relation.c, Line: 62, Context: TDS
2022-04-22 11:56:53.262 EDT [1186838] CONTEXT:  TDS Protocol: Message Type: SQL BATCH, Phase: TDS_REQUEST_PHASE_PROCESS. Processing SQL Batch Request
2022-04-22 11:56:53.898 EDT [1144591] LOG:  message_type: Remote Procedure Call (3) rpc_packet_type: sp_executesql
2022-04-22 11:56:53.898 EDT [1144591] CONTEXT:  TDS Protocol: Message Type: RPC, SP Type: SP_EXECUTESQL, Phase: TDS_REQUEST_PHASE_FETCH. Fetching RPC Request
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by robverschoor** [comment] 2022-04-22 16:43
I cannot reproduce this on any Babelfish version - it works fine for me. 
That said, some time ago we ran into a bug which seemed to have as a side effect that you couldn't create such #temp tables anymore.  
Can you drop your database? If so, please drop and recreate. If not, please delete the cluster and recreate it. 

Which Babelfish version are you running exactly? Please always specify the output of `SELECT CAST(SERVERPROPERTY('BabelfishVersion') AS VARCHAR) ` when reporting an issue

**Comment by sherbert** [comment] 2022-04-22 21:33
Apologies, Babelfish version is 1.2.0.

Dropping and recreating the database did not fix the issue, but deleting and recreating the cluster did. I have a snapshot of the old cluster if there is any value to it for debugging the state that was breaking this.

**Comment by robverschoor** [comment] 2022-04-27 19:07
The next release of Babelfish should contain a fix for this issue.

**Comment by suprio-amzn** [comment] 2022-12-01 19:29
@sherbert: Were you able to solve the above issue by using the latest version of Babelfish?

**Comment by sherbert** [comment] 2022-12-01 20:56
I haven't run into it since I deleted and recreated the cluster that originally had the problem.

**Comment by suprio-amzn** [comment] 2022-12-02 00:51
Ok, I'll close the issue for now. Please open a new one if you encounter a similar problem.

**Closed as completed by suprio-amzn** 2022-12-02 00:51 UTC
Labels: bug, Pending Response
