### ISSUE TITLE
[Bug]: scope_identity Taking Minutes to Return

### ISSUE THREAD

**Issue by KevinDJones** [babelfish-for-postgresql/babelfish_extensions#727] opened 2022-10-25 05:16 UTC
### What happened?

I have a good sized table (~45 millions records) that I am trying to migrate from SQL Server. It has a `bigint` identity column as the PK. I've loaded the table using bcp. 

When inserting records, the query that runs is 
```
insert into table (columns) values ('values');
SELECT top 1 [ID]
FROM table
WHERE @@ROWCOUNT = 1 AND [ID] = scope_identity()
```

This takes about 3 minutes. If I do the equivalent query in Postgres:
```
insert into table (columns) values ('values')
returning id
```
It returns immediately. 

Here is the returned plan:
```
Limit  (cost=0.00..2056.90 rows=1 width=8) (actual rows=1 loops=1)
  ->  Seq Scan on table  (cost=0.00..2367488.76 rows=1151 width=8) (actual rows=1 loops=1)
        Filter: ((rowcount() = 1) AND ((id)::numeric = (((babelfish_get_last_identity())::numeric(38,0))::numeric(38,0))::numeric))
        Rows Removed by Filter: 45793330
```

I have some other, much smaller tables, that don't have this problem at all. Is it just the size? The way it was populated? There's no traffic and the machine is way over provisioned. In AWS.

### Version

BABEL_1_X_DEV (Default)

### Extension

babelfishpg_tsql (Default)

### Which flavor of Linux are you using when you see the bug?

Amazon Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by robverschoor** [comment] 2022-10-25 10:26
This is a known issue. You can try the following, pending improvements in future Babelfish releases:

1. In PG, mark function sys.scope_identity() as STABLE (this will be the default in v.2.2.0)
2. If (1) does not do the trick, create an index `CREATE INDEX your_index_name ON table ((your_identity_column::numeric));` (and run ANALYZE)

**Comment by kevin-jones-cbs** [comment] 2022-10-25 16:33
Thanks @rcv-aws for the response. I can't do number 1 since I'm in AWS and I `must be owner of function scope_identify`. I created the index and ran ANALYZE but still no luck, same 3 minute response time. 

Do you know what causes the issue? Wondering if there's a workaround I can try. Or is it just large tables? I created the records with identity insert on and started the ID in the millions. I don't necessarily have to do that, if I started at 1 would it make a difference?

**Comment by robverschoor** [comment] 2022-10-25 16:37
We have seen an index on the identity column not being used when queried against SCOPE_IDENTITY() due to that function not being declared as STABLE, thus leading to a table scan.

**Comment by robverschoor** [comment] 2022-10-28 10:07
The problem is that PG performs a table scan because the search argument (SCOPE_IDENTITY()) is not a STABLE function and therefore cannot be used for an index lookup. A workaround would be to first select the SCOPE_IDENTITY value in a bigint variable, and use that variable for the search argument

**Comment by suprio-amzn** [comment] 2023-04-02 04:36
@kevin-jones-cbs, @KevinDJones: A fix for this issue has been merged and is available as part of this commit (https://github.com/babelfish-for-postgresql/babelfish_extensions/commit/43f4dd3018244432c91129bfa2f7ecb630856b81).

**Closed as completed by suprio-amzn** 2023-04-02 04:36 UTC
Labels: bug
