### ISSUE TITLE
[Question]:  Is datetime to integer conversion supported somehow?

### ISSUE THREAD

**Issue by williamgosse** [babelfish-for-postgresql/babelfish_extensions#106] opened 2022-03-28 13:26 UTC
### Contact Details

bgosse@aresprism

### What's the question?

I have a question! Is dateime to integer conversion supported somehow? Im seeing the following error in a view I'm trying to create:

Msg 33557097, Level 16, State 1, Line 97
UNION could not convert type datetime to integer

I'm told that this view creates fine in a normal sql server.

I tried to for the datetime field to a  date but get the following error when I use the CONVERT function more then once in the same select statement:

Msg 33557097, Level 16, State 1, Line 66
column "babelfish_conv_helper_to_date" specified more than once

Any thoughts or help on this would be much appreciated.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by robverschoor** [comment] 2022-03-28 13:45
The numeric representation of DATETIME is not currently supported in Babelfish. For converting numeric to DATETIME(not the other way around) , you can use the **-rewrite** option on the Babelfish Compass tool, this will rewrite the numeric expression in a way that will work on Babalfish. 
Download Compass here: https://github.com/babelfish-for-postgresql/babelfish_compass/releases/latest

**Comment by williamgosse** [comment] 2022-03-28 19:28
This was another weird fix to what seem to be a totally unrelated column in each of the unions in the view.  Providing a default value, in this case a 0, made the error go away.

**Comment by robverschoor** [comment] 2022-03-28 20:09
There are some known issues related to implicit datatype conversion for different branches of a UNION. At least some of those were fixed, but if you can provide a reproduction I'd like to verify whether we have your issue on the radar.

**Comment by suprio-amzn** [comment] 2023-04-23 16:49
> _There are some known issues related to implicit datatype conversion for different branches of a UNION. At least some of those were fixed, but if you can provide a reproduction I'd like to verify whether we have your issue on the radar._

@williamgosse: I am closing this issue since we don't have a reproduction for the above but the other part  \[ https://github.com/babelfish-for-postgresql/babelfish_extensions/issues/106#issuecomment-1080672018 \] we have fix that is part of this commit (https://github.com/babelfish-for-postgresql/babelfish_extensions/commit/8a387d1fc486ee4b383de6d2f1aef3e196a7dd11) which will be available as part of the next release.

**Closed as completed by suprio-amzn** 2023-04-23 16:49 UTC
Labels: question, Pending Response
