### ISSUE TITLE
[Bug]: Select SERVERPROPERTY('MachineName') as MachineName returns null

### ISSUE THREAD

**Issue by williamgosse** [babelfish-for-postgresql/babelfish_extensions#113] opened 2022-04-04 16:19 UTC
### Contact Details

bgosse@aresprism.com

### What happened?

A bug happened! Select SERVERPROPERTY('MachineName') as MachineName returns null. Shouldn't return a hostname?

Im using babelfish 1.10 on AWS Aurora Postgres 13.5.

![image](https://user-images.githubusercontent.com/27444380/161599015-df984cde-8d5e-4132-a6e3-fda2b9385340.png)

### Version

BABEL_1_X_DEV (Default)

### Extension

babelfishpg_tsql (Default)

### What flavour of Linux are you running into the bug?

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by robverschoor** [comment] 2022-04-13 09:39
This is not a bug; this property is not currently supported (the same applies to various other properties). Please check the Babelfish documentation for a list of supported properties.

**Comment by max-webster** [comment] 2022-05-24 16:32
In particular, on page: https://babelfishpg.org/docs/usage/limitations-of-babelfish/

SERVERPROPERTY(): | The following values are supported in 1.2.0: Babelfish, Collation, CollationID, Edition, EditionID, EngineEdition, ServerName, LicenseType, ProductVersion, ProductMajorVersion, ProductMinorVersion, IsSingleUser, IsIntegratedSecurityOnly, IsLocalDB, IsAdvancedAnalyticsInstalled, IsBigDataCluster, IsPolyBaseInstalled, IsFullTextInstalled, IsXTPSupported

**Comment by max-webster** [comment] 2022-06-03 20:08
Since it's a documented limitation, I'll close the issue now.

**Closed as completed** 2022-07-18 02:24 UTC
