### ISSUE TITLE
[Bug]: segfault selecting computed column

### ISSUE THREAD

**Issue by sherbert** [babelfish-for-postgresql/babelfish_extensions#117] opened 2022-04-15 14:46 UTC
### Contact Details

herbert@dc-energy.com

### What happened?

segfault on trying to select from a table with this definition:
```
CREATE TABLE [dbo].[bar] (
    [baz] [int] NULL,
    [qux] AS ISNULL(CONVERT([CHAR](1), 'A'), 'B')
)
```
I needed the whole `ISNULL(CONVERT(` to get the segfault. Neither `AS ISNULL('A', 'B')` nor `AS CONVERT([CHAR](1), 'A')` would cause the issue.

```
1> CREATE DATABASE [foo]
2> GO
1> USE foo
2> GO
Changed database context to 'foo'.
1> CREATE TABLE [dbo].[bar] (
2>     [baz] [int] NULL,
3>     [qux] AS ISNULL(CONVERT([CHAR](1), 'A'), 'B')
4> )
5> GO
1> SELECT [qux] FROM [dbo].[bar]
2> GO
TCP Provider: Error code 0x2746
Communication link failure
```

The same sequence against SQL Server 2019 Express works as expected and gives:
```
1> SELECT [qux] FROM [dbo].[bar]
2> GO
qux
---

(0 rows affected)
```

### Version

BABEL_1_X_DEV (Default)

### Extension

babelfishpg_tsql (Default)

### What flavour of Linux are you running into the bug?

Ubuntu (Default)

### Relevant log output

```shell
2022-04-15 10:37:46.862 EDT [1023226] LOG:  server process (PID 1023246) was terminated by signal 11: Segmentation fault
2022-04-15 10:37:46.862 EDT [1023226] DETAIL:  Failed process was running: SELECT * FROM [dbo].[bar]

2022-04-15 10:37:46.862 EDT [1023226] LOG:  terminating any other active server processes
2022-04-15 10:37:46.862 EDT [1023232] WARNING:  terminating connection because of crash of another server process
2022-04-15 10:37:46.862 EDT [1023232] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2022-04-15 10:37:46.862 EDT [1023232] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2022-04-15 10:37:46.872 EDT [1023226] LOG:  all server processes terminated; reinitializing
2022-04-15 10:37:46.929 EDT [1023340] LOG:  database system was interrupted; last known up at 2022-04-15 10:34:43 EDT
2022-04-15 10:37:48.405 EDT [1023340] LOG:  database system was not properly shut down; automatic recovery in progress
2022-04-15 10:37:48.418 EDT [1023340] LOG:  redo starts at 1/97A1A900
2022-04-15 10:37:48.461 EDT [1023340] LOG:  invalid record length at 1/97A246A8: wanted 24, got 0
2022-04-15 10:37:48.461 EDT [1023340] LOG:  redo done at 1/97A24150
2022-04-15 10:37:48.504 EDT [1023226] LOG:  database system is ready to accept connections
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by robverschoor** [comment] 2022-04-15 17:13
This is a bug. We're looking into it. 
Thanks for reporting it.

**Comment by suprio-amzn** [comment] 2023-04-02 04:31
@sherbert : A fix to the issue is available and is merged as part of commit (https://github.com/babelfish-for-postgresql/postgresql_modified_for_babelfish/commit/605ee8e9ab1ebc07ecca3576b4453497c1bffdc5).

**Closed as completed by suprio-amzn** 2023-04-02 04:31 UTC
Labels: bug
