### ISSUE TITLE
[Bug]: Perl version related issue for make configure

### ISSUE THREAD

**Issue by lomatus** [babelfish-for-postgresql/babelfish_extensions#23] opened 2021-11-05 18:17 UTC
### What happened?

Error to make when PERL version is 5.22+

### Version

BABEL_1_X_DEV (Default)

### Extension

babelfishpg_tsql (Default)

### What flavour of Linux are you running into the bug?

Ubuntu (Default)

### Relevant log output

```shell
'/usr/bin/perl' src/backend_parser/include.pl src/backend_parser gram.y < /home/lomatus/postgresql_modified_for_babelfish/src/backend/parser/gram.y > src/backend_parser/gram-backend.y
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/^<.*>{ <-- HERE $/ at src/backend_parser/include.pl line 147.
Makefile:183: recipe for target 'src/backend_parser/gram-backend.y' failed
make: *** [src/backend_parser/gram-backend.y] Error 255
make: *** Deleting file 'src/backend_parser/gram-backend.y'
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by lomatus** [comment] 2021-11-05 18:24
If perl is 5.20+, fix at line 147:
`
elsif ($arr[$fieldIndexer] =~ /^<.*>\{$/) # special handling for lex grammar "<...>{" not to add #line directive
`

**Comment by sangilsong** [comment] 2021-12-16 00:23
duplicate of https://github.com/babelfish-for-postgresql/babelfish_extensions/issues/32. already fixed.

**Closed as completed by sangilsong** 2021-12-16 00:23 UTC
Labels: bug, babelfishpg_tsql
